version: '3'
services:
  dj_mysql:
    container_name: dj-mysql
    image: mysql/mysql-server:8.0.27
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_DATABASE: dj
      MYSQL_ROOT_PASSWORD: wd0202
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - /opt/docker-volumes/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - dj
  dj_web:
    container_name: dj-web
    build: .
    command: gunicorn tourweb.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --log-level=debug
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - /opt/docker-volumes/dj-static:/code/static
      - /opt/docker-volumes/media:/code/media
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - dj_mysql
    restart: always
    networks:
      - dj

networks:
  dj: